GET http://localhost:5000/blogs/getblogs

###

POST http://localhost:5000/blogs/save
Content-Type: application/json

{
    "name": "marta",
    "password": "lagarta"
}

###
GET http://localhost:5000/blogs/getusers

###

POST http://localhost:5000/blogs/login
Content-Type: application/json

{
    "name": "patminero",
    "pass": "#SolarEclipse20!"
}

###

POST http://localhost:5000/blogs/message
Content-Type: application/json

{
    "name": "patminero",
    "email": "email@email.com",
    "message": "hola cuaquicuo"
}
